import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";

import React from "react";

export const metadata: Metadata = {
  title: "Nextjs 13",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>{children}</body>
      </ClerkProvider>
    </html>
  );
}
